[package]
name = "text_editor"
version = "0.1.0"
authors = ["isaiahbarnwell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
